//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 04:21:55 PM CEST 
//


package rs.gov.parlament.propisi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="deo" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="glava" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;choice&gt;
 *                               &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                               &lt;element name="odeljak" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                 &lt;complexType&gt;
 *                                   &lt;complexContent&gt;
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                       &lt;choice&gt;
 *                                         &lt;element name="pododeljak" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                           &lt;complexType&gt;
 *                                             &lt;complexContent&gt;
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                 &lt;sequence&gt;
 *                                                   &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded"/&gt;
 *                                                 &lt;/sequence&gt;
 *                                                 &lt;attribute name="naziv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                 &lt;attribute name="br" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                               &lt;/restriction&gt;
 *                                             &lt;/complexContent&gt;
 *                                           &lt;/complexType&gt;
 *                                         &lt;/element&gt;
 *                                         &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                                       &lt;/choice&gt;
 *                                     &lt;/restriction&gt;
 *                                   &lt;/complexContent&gt;
 *                                 &lt;/complexType&gt;
 *                               &lt;/element&gt;
 *                             &lt;/choice&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="redBr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute name="naziv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="naziv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deo",
    "status"
})
@XmlRootElement(name = "zakon")
public class Zakon {

    @XmlElement(required = true)
    protected List<Zakon.Deo> deo;
    @XmlElement(required = true)
    protected String status;
    @XmlAttribute(name = "naziv", required = true)
    protected String naziv;
    @XmlAttribute(name = "ID", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;

    /**
     * Gets the value of the deo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Zakon.Deo }
     * 
     * 
     */
    public List<Zakon.Deo> getDeo() {
        if (deo == null) {
            deo = new ArrayList<Zakon.Deo>();
        }
        return this.deo;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="glava" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;choice&gt;
     *                     &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                     &lt;element name="odeljak" maxOccurs="unbounded" minOccurs="0"&gt;
     *                       &lt;complexType&gt;
     *                         &lt;complexContent&gt;
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                             &lt;choice&gt;
     *                               &lt;element name="pododeljak" maxOccurs="unbounded" minOccurs="0"&gt;
     *                                 &lt;complexType&gt;
     *                                   &lt;complexContent&gt;
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                       &lt;sequence&gt;
     *                                         &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded"/&gt;
     *                                       &lt;/sequence&gt;
     *                                       &lt;attribute name="naziv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                       &lt;attribute name="br" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                     &lt;/restriction&gt;
     *                                   &lt;/complexContent&gt;
     *                                 &lt;/complexType&gt;
     *                               &lt;/element&gt;
     *                               &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                             &lt;/choice&gt;
     *                           &lt;/restriction&gt;
     *                         &lt;/complexContent&gt;
     *                       &lt;/complexType&gt;
     *                     &lt;/element&gt;
     *                   &lt;/choice&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="redBr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *       &lt;attribute name="naziv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clan",
        "glava"
    })
    public static class Deo {

        protected List<Clan> clan;
        protected List<Zakon.Deo.Glava> glava;
        @XmlAttribute(name = "naziv", required = true)
        protected String naziv;
        @XmlAttribute(name = "ID", required = true)
        protected String id;

        /**
         * Gets the value of the clan property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the clan property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClan().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Clan }
         * 
         * 
         */
        public List<Clan> getClan() {
            if (clan == null) {
                clan = new ArrayList<Clan>();
            }
            return this.clan;
        }

        /**
         * Gets the value of the glava property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the glava property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGlava().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Zakon.Deo.Glava }
         * 
         * 
         */
        public List<Zakon.Deo.Glava> getGlava() {
            if (glava == null) {
                glava = new ArrayList<Zakon.Deo.Glava>();
            }
            return this.glava;
        }

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;choice&gt;
         *           &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded" minOccurs="0"/&gt;
         *           &lt;element name="odeljak" maxOccurs="unbounded" minOccurs="0"&gt;
         *             &lt;complexType&gt;
         *               &lt;complexContent&gt;
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                   &lt;choice&gt;
         *                     &lt;element name="pododeljak" maxOccurs="unbounded" minOccurs="0"&gt;
         *                       &lt;complexType&gt;
         *                         &lt;complexContent&gt;
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                             &lt;sequence&gt;
         *                               &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded"/&gt;
         *                             &lt;/sequence&gt;
         *                             &lt;attribute name="naziv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                             &lt;attribute name="br" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                           &lt;/restriction&gt;
         *                         &lt;/complexContent&gt;
         *                       &lt;/complexType&gt;
         *                     &lt;/element&gt;
         *                     &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded" minOccurs="0"/&gt;
         *                   &lt;/choice&gt;
         *                 &lt;/restriction&gt;
         *               &lt;/complexContent&gt;
         *             &lt;/complexType&gt;
         *           &lt;/element&gt;
         *         &lt;/choice&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="redBr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "clan",
            "odeljak"
        })
        public static class Glava {

            @XmlElement(required = true)
            protected String title;
            protected List<Clan> clan;
            protected List<Zakon.Deo.Glava.Odeljak> odeljak;
            @XmlAttribute(name = "redBr", required = true)
            protected String redBr;

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the clan property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the clan property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getClan().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Clan }
             * 
             * 
             */
            public List<Clan> getClan() {
                if (clan == null) {
                    clan = new ArrayList<Clan>();
                }
                return this.clan;
            }

            /**
             * Gets the value of the odeljak property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the odeljak property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOdeljak().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Zakon.Deo.Glava.Odeljak }
             * 
             * 
             */
            public List<Zakon.Deo.Glava.Odeljak> getOdeljak() {
                if (odeljak == null) {
                    odeljak = new ArrayList<Zakon.Deo.Glava.Odeljak>();
                }
                return this.odeljak;
            }

            /**
             * Gets the value of the redBr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRedBr() {
                return redBr;
            }

            /**
             * Sets the value of the redBr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRedBr(String value) {
                this.redBr = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;choice&gt;
             *         &lt;element name="pododeljak" maxOccurs="unbounded" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded"/&gt;
             *                 &lt;/sequence&gt;
             *                 &lt;attribute name="naziv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                 &lt;attribute name="br" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded" minOccurs="0"/&gt;
             *       &lt;/choice&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "pododeljak",
                "clan"
            })
            public static class Odeljak {

                protected List<Zakon.Deo.Glava.Odeljak.Pododeljak> pododeljak;
                protected List<Clan> clan;

                /**
                 * Gets the value of the pododeljak property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the pododeljak property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPododeljak().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Zakon.Deo.Glava.Odeljak.Pododeljak }
                 * 
                 * 
                 */
                public List<Zakon.Deo.Glava.Odeljak.Pododeljak> getPododeljak() {
                    if (pododeljak == null) {
                        pododeljak = new ArrayList<Zakon.Deo.Glava.Odeljak.Pododeljak>();
                    }
                    return this.pododeljak;
                }

                /**
                 * Gets the value of the clan property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the clan property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getClan().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Clan }
                 * 
                 * 
                 */
                public List<Clan> getClan() {
                    if (clan == null) {
                        clan = new ArrayList<Clan>();
                    }
                    return this.clan;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element ref="{http://www.parlament.gov.rs/propisi}clan" maxOccurs="unbounded"/&gt;
                 *       &lt;/sequence&gt;
                 *       &lt;attribute name="naziv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *       &lt;attribute name="br" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "clan"
                })
                public static class Pododeljak {

                    @XmlElement(required = true)
                    protected List<Clan> clan;
                    @XmlAttribute(name = "naziv", required = true)
                    protected String naziv;
                    @XmlAttribute(name = "br", required = true)
                    protected String br;

                    /**
                     * Gets the value of the clan property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the clan property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getClan().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Clan }
                     * 
                     * 
                     */
                    public List<Clan> getClan() {
                        if (clan == null) {
                            clan = new ArrayList<Clan>();
                        }
                        return this.clan;
                    }

                    /**
                     * Gets the value of the naziv property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNaziv() {
                        return naziv;
                    }

                    /**
                     * Sets the value of the naziv property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNaziv(String value) {
                        this.naziv = value;
                    }

                    /**
                     * Gets the value of the br property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBr() {
                        return br;
                    }

                    /**
                     * Sets the value of the br property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBr(String value) {
                        this.br = value;
                    }

                }

            }

        }

    }
}
