//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 04:21:55 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.parlament.gov.rs/propisi", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package src.rs.gov.parlament.propisi;
